FROM python:3.12-slim@sha256:f77ac9e44ae96ef2c90b8053ea08c31f8be030f824196b0ae4db6d462c84e51f
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements ./requirements
COPY pyproject.toml ./
COPY apps ./apps
COPY packages ./packages
COPY migrations ./migrations
COPY alembic.ini ./
RUN pip install --no-cache-dir --require-hashes -r requirements/build.txt \
    && pip install --no-cache-dir --require-hashes -r requirements/runtime.txt \
    && pip install --no-cache-dir --no-deps --no-build-isolation . \
    && pip check
USER 10001:10001
